### ISSUE TITLE
Lightning Speed

### ISSUE THREAD

**Issue by duchonic** [maggie-j-liu/advent-of-code-2022#1]
Hi Maggie

Congrats to finish top100!
We have a small coding learning group and checked your solution for todays aoc. 

How do you write 25 lines of code in 1min11sec?

Do you have any tips for us?

Have a nice AOC

**Comment by maggie-j-liu** [comment]
hi!

my actual solution for part 1 was this
```js
import getInput from "../utils/getInput.js";

const input = await getInput(import.meta.url);
const groups = input.split("\n\n");

let best = 0;
for (const group of groups) {
  const lines = group.split("\n");
  let sum = 0;
  for (const line of lines) {
    sum += parseInt(line);
  }
  best = Math.max(best, sum);
}
console.log(best);
```

the top few lines are actually automatically populated from my template, so it's really ~10 lines of code 😆
i have a script to download the input, as well as templated lines to parse the input, which saves a lot of time. other than that, i don't really have any tips... skim the problem & think fast, i guess?

hope you enjoy AOC as well!

**Comment by duchonic** [comment]
Hi

Thanks for the answer. I got the leaderboard wrong, 
thought it's first start and then second start...

So 1min11sec still very fast, respect.

Enjoy
